=== jedsg777/pos-2026-tarefas/tarefa01/definicoes.dtd
<!ELEMENT cardapio (prato+)>

<!ELEMENT prato (nome, descricao, ingredientes, preco, calorias, tempoPreparo)>
<!ATTLIST prato id ID #REQUIRED>

<!ELEMENT nome (#PCDATA)>
<!ELEMENT descricao (#PCDATA)>

<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>

<!ELEMENT preco (#PCDATA)>
<!ATTLIST preco moeda (BRL) "BRL">
<!ENTITY reais "R$">

<!ELEMENT calorias (#PCDATA)>
<!ELEMENT tempoPreparo (#PCDATA)>

=== jedsg777/pos-2026-tarefas/tarefa01/cardapio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cardapio SYSTEM "definicoes.dtd">
<cardapio>
    <prato id="Pra01">
        <nome>pirao</nome>
        <descricao>graxa de frango com farinha</descricao>
        <ingredientes>
            <ingrediente>graxa de frango</ingrediente>
            <ingrediente>farinha</ingrediente>
        </ingredientes>
        <preco moeda="BRL">&reais; 15</preco>
        <calorias>1000kcal</calorias>
        <tempoPreparo>20min</tempoPreparo>
    </prato>

    <prato id="Pra02">
        <nome>farofa</nome>
        <descricao>nao tem como descrever farofa muito bem</descricao>
        <ingredientes>
            <ingrediente>farinha</ingrediente>
            <ingrediente>manteiga</ingrediente>
            <ingrediente>bacon</ingrediente>
            <ingrediente>cebola</ingrediente>
        </ingredientes>
        <preco moeda="BRL">&reais; 10</preco>
        <calorias>500kcal</calorias>
        <tempoPreparo>40min</tempoPreparo>
    </prato>

    <prato id="Pra03">
        <nome>arroz com feijao</nome>
        <descricao>arroz e feijao</descricao>
        <ingredientes>
            <ingrediente>feijao</ingrediente>
            <ingrediente>Arroz</ingrediente>
        </ingredientes>
        <preco moeda="BRL">&reais; 20</preco>
        <calorias>700kcal</calorias>
        <tempoPreparo>60min</tempoPreparo>
    </prato>

    <prato id="Pra04">
        <nome>churrasco de picanha</nome>
        <descricao>picanha grelhada na churrasqueira</descricao>
        <ingredientes>
            <ingrediente>Picanha</ingrediente>
        </ingredientes>
        <preco moeda="BRL">&reais; 70</preco>
        <calorias>800kcal</calorias>
        <tempoPreparo>30min</tempoPreparo>
    </prato>

    <prato id="Pra05">
        <nome>salada</nome>
        <descricao>eu nao compro isso</descricao>
        <ingredientes>
            <ingrediente>alface</ingrediente>
            <ingrediente>tomate</ingrediente>
            <ingrediente>ovo</ingrediente>
            <ingrediente>pepino</ingrediente>
        </ingredientes>
        <preco moeda="BRL">&reais; 30</preco>
        <calorias>200kcal</calorias>
        <tempoPreparo>20min</tempoPreparo>
    </prato>
</cardapio>
